# Generated by Django 3.0.4 on 2020-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
