# Generated by Django 3.0.4 on 2020-05-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='slug',
        ),
    ]
