# Generated by Django 3.0.4 on 2020-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_pet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
